language: python
python:
  - "2.7"
sudo: required
env:
  global:
    - Z3_DIR=/usr/lib/python2.7/dist-packages/z3
cache:
  directories:
    - $Z3_DIR
before_script:
  - if [[ ! -f "$Z3_DIR/z3.py" ]]; then
      wget https://github.com/Z3Prover/z3/archive/z3-4.5.0.tar.gz;
      tar xzf z3-4.5.0.tar.gz;
      cd z3-z3-4.5.0;
      python scripts/mk_make.py --python;
      cd build;
      make;
      sudo make install;
    else echo "using z3 from cache"; fi
  - ls /usr/lib/python2.7/dist-packages
  - ls $Z3_DIR
script:
  - cd $TRAVIS_BUILD_DIR
  - oyente -s test.sol
