language: python
python:
  - "2.7"
env:
  global:
    - Z3_DIR=$HOME/virtualenv/python2.7.13/test
cache:
  directories:
    - $Z3_DIR
before_script:
  - if [[ ! -f "$Z3_DIR/demo.txt" ]]; then
      mkdir -p $Z3_DIR;
      touch $Z3_DIR/demo.txt;
    else echo "using z3 from cache"; fi
  - ls $HOME/virtualenv/python2.7.13
  - ls $Z3_DIR
script:
  - cd $TRAVIS_BUILD_DIR
  - ls
