language: python
python:
  - "2.7"
env:
  global:
    - Z3_DIR=~/virtualenv/python2.7/lib/python2.7/site-packages/z3
cache:
  pip: true
  custom_install: true
  directories:
    - ~/virtualenv/python2.7/lib
install:
  - pip install requests
  - pip install web3
  - pip uninstall oyente
  - pip install oyente
before_script:
  - if [[ ! -f "$Z3_DIR/__init__.py" ]]; then
      cd;
      wget https://github.com/Z3Prover/z3/archive/z3-4.5.0.tar.gz;
      tar xzf z3-4.5.0.tar.gz;
      cd z3-z3-4.5.0;
      python scripts/mk_make.py --python;
      cd build;
      make;
      sudo make install;
    else echo "using z3 from cache"; fi
script:
  - cd $TRAVIS_BUILD_DIR
  - oyente -s test.sol

